import { Mutant, Plugin } from '@systemfsoftware/stryker-js-plugin-interface'
import * as S from 'effect/Schema'

import { SpanAttributeCount, SpanAttributeText, type SpanMember } from './SpanTaxonomy.schema.js'

const protocolMethods: ReadonlyArray<string> = [
  ...new Set([
    ...Plugin.CheckerRpcs.requests.keys(),
    ...Plugin.TestRunnerRpcs.requests.keys(),
    ...Plugin.ReporterRpcs.requests.keys(),
  ]),
].sort()

export const Spans = {
  checkerCheck: {
    name: 'stryker.checker.check',
    attributes: { 'stryker.checker.name': SpanAttributeText, 'stryker.mutants.count': SpanAttributeCount },
  },
  checkerCheckPlans: { name: 'stryker.checker.check_plans', attributes: {} },
  checkerGroup: {
    name: 'stryker.checker.group',
    attributes: { 'stryker.checker.name': SpanAttributeText, 'stryker.mutants.count': SpanAttributeCount },
  },
  checkerGroupPlans: { name: 'stryker.checker.group_plans', attributes: {} },
  checkerLogSkipped: { name: 'stryker.checker.log_skipped', attributes: {} },
  checkerPoolCheckPlans: { name: 'stryker.checker_pool.check_plans', attributes: {} },
  checkerPoolSplitChecked: { name: 'stryker.checker_pool.split_checked', attributes: {} },
  checkerRecordSkipped: { name: 'stryker.checker.record_skipped', attributes: {} },
  cliRun: {
    name: 'stryker.cli.run',
    attributes: {
      'stryker.run.outcome': SpanAttributeText,
      'stryker.run.exit_code': SpanAttributeCount,
      'stryker.run.error': SpanAttributeText,
    },
  },
  commandRunnerRun: { name: 'stryker.command_runner.run', attributes: {} },
  concurrency: { name: 'stryker.concurrency', attributes: {} },
  configDiscover: { name: 'stryker.config.discover', attributes: {} },
  configExists: { name: 'stryker.config.exists', attributes: {} },
  configExpectedFile: { name: 'stryker.config.expectedFile', attributes: {} },
  configExtends: { name: 'stryker.config.extends', attributes: {} },
  configExtendsChild: { name: 'stryker.config.extendsChild', attributes: {} },
  configExtendsStep: { name: 'stryker.config.extendsStep', attributes: {} },
  configLoad: { name: 'stryker.config.load', attributes: {} },
  configLoadOptions: { name: 'stryker.config.loadOptions', attributes: {} },
  configRead: { name: 'stryker.config_read', attributes: {} },
  configReadDocument: { name: 'stryker.config.readDocument', attributes: {} },
  configReadModule: { name: 'stryker.config.readModule', attributes: {} },
  configReadRun: { name: 'stryker.config.readRun', attributes: {} },
  dryRun: { name: 'stryker.dry_run', attributes: {} },
  dryRunComplete: { name: 'stryker.dry_run.complete', attributes: {} },
  dryRunPhase: { name: 'dryRun', attributes: {} },
  dryRunResolveFiles: { name: 'stryker.dry_run.resolve_files', attributes: {} },
  dryRunWriteFailed: { name: 'stryker.dry_run.write_failed', attributes: {} },
  dryRunWritePassed: { name: 'stryker.dry_run.write_passed', attributes: {} },
  frameworkClaimantList: { name: 'stryker.framework_claimant.list', attributes: {} },
  frameworkClaimantOf: { name: 'stryker.framework_claimant.of', attributes: {} },
  htmlReportReadBundleFromDisk: { name: 'html_report.read_bundle_from_disk', attributes: {} },
  htmlReportWrite: { name: 'html_report.write', attributes: {} },
  htmlReportWriteBundleFromDisk: { name: 'html_report.write_bundle_from_disk', attributes: {} },
  htmlReportWriteFile: { name: 'html_report.write_file', attributes: {} },
  incrementalReuse: { name: 'stryker.incremental_reuse', attributes: {} },
  incrementalReuseRead: { name: 'stryker.incremental_reuse.read', attributes: {} },
  instrument: { name: 'stryker.instrument', attributes: {} },
  instrumentDisableTypeChecks: { name: 'stryker.instrument.disableTypeChecks', attributes: {} },
  instrumentFrameworkEntryParse: { name: 'stryker.instrument.framework_entry.parse', attributes: {} },
  instrumentFrameworkEntryTransform: { name: 'stryker.instrument.framework_entry.transform', attributes: {} },
  instrumentGather: { name: 'stryker.instrument.gather', attributes: {} },
  instrumentOfferSkips: { name: 'stryker.instrument.offer-skips', attributes: {} },
  instrumentParserParseJS: { name: 'stryker.instrument.parser.parseJS', attributes: {} },
  instrumentParserParseTS: { name: 'stryker.instrument.parser.parseTS', attributes: {} },
  instrumentParserParseTsx: { name: 'stryker.instrument.parser.parseTsx', attributes: {} },
  instrumentParserParseWithOxc: { name: 'stryker.instrument.parser.parseWithOxc', attributes: {} },
  instrumentPhase: { name: 'instrument', attributes: { fileCount: SpanAttributeCount } },
  instrumentReadFiles: { name: 'stryker.instrument.read_files', attributes: {} },
  instrumentReportSkips: { name: 'stryker.instrument.report-skips', attributes: {} },
  instrumentTransformScript: { name: 'stryker.instrument.transform.script', attributes: {} },
  loadConfig: { name: 'stryker.load_config', attributes: {} },
  mergeReports: { name: 'stryker.merge_reports', attributes: {} },
  mergeReportsCollectPartDirs: { name: 'stryker.merge_reports.collect_part_dirs', attributes: {} },
  mergeReportsDirectoryExists: { name: 'stryker.merge_reports.directory_exists', attributes: {} },
  mergeReportsEncodeReport: { name: 'stryker.merge_reports.encode_report', attributes: {} },
  mergeReportsFail: { name: 'stryker.merge_reports.fail', attributes: {} },
  mergeReportsGather: { name: 'stryker.merge_reports.gather', attributes: {} },
  mergeReportsListNames: { name: 'stryker.merge_reports.list_names', attributes: {} },
  mergeReportsPutFile: { name: 'stryker.merge_reports.put_file', attributes: {} },
  mergeReportsReadPart: { name: 'stryker.merge_reports.read_part', attributes: {} },
  mergeReportsReadText: { name: 'stryker.merge_reports.read_text', attributes: {} },
  mergeReportsRefuseCommand: { name: 'stryker.merge_reports.refuse_command', attributes: {} },
  mergeReportsRefuseParts: { name: 'stryker.merge_reports.refuse_parts', attributes: {} },
  mergeReportsRenderHtml: { name: 'stryker.merge_reports.render_html', attributes: {} },
  mergeReportsWriteAbsent: { name: 'stryker.merge_reports.write_absent', attributes: {} },
  mergeReportsWriteFiles: { name: 'stryker.merge_reports.write_files', attributes: {} },
  mergeReportsWriteHtml: { name: 'stryker.merge_reports.write_html', attributes: {} },
  mergeReportsWriteMerged: { name: 'stryker.merge_reports.write_merged', attributes: {} },
  mutantRun: { name: 'stryker.mutant_run', attributes: {} },
  mutationReportingAssembleReport: { name: 'stryker.mutationReporting.assembleReport', attributes: {} },
  mutationReportingCheckpoint: { name: 'stryker.mutationReporting.checkpoint', attributes: {} },
  mutationReportingDiscoverDependencies: { name: 'stryker.mutationReporting.discoverDependencies', attributes: {} },
  mutationReportingEmitVerdict: { name: 'stryker.mutationReporting.emitVerdict', attributes: {} },
  mutationReportingManifestVersion: { name: 'stryker.mutationReporting.manifestVersion', attributes: {} },
  mutationReportingMutationTestReport: { name: 'stryker.mutationReporting.mutationTestReport', attributes: {} },
  mutationReportingReadMutatedSources: { name: 'stryker.mutationReporting.readMutatedSources', attributes: {} },
  mutationReportingReadTestSources: { name: 'stryker.mutationReporting.readTestSources', attributes: {} },
  mutationReportingReportAll: { name: 'stryker.mutationReporting.reportAll', attributes: {} },
  mutationReportingSlimIncrementalReport: { name: 'stryker.mutationReporting.slimIncrementalReport', attributes: {} },
  mutationReportingWriteAtomic: { name: 'stryker.mutationReporting.writeAtomic', attributes: {} },
  mutationReportingWriteIncrementalReport: { name: 'stryker.mutationReporting.writeIncrementalReport', attributes: {} },
  mutationTest: { name: 'stryker.mutation_test', attributes: {} },
  mutationTestBatch: {
    name: 'mutationTest.batch',
    attributes: { total: SpanAttributeCount, testRunners: SpanAttributeCount },
  },
  mutationTestCheckerScope: { name: 'stryker.mutation_test.checker_scope', attributes: {} },
  mutationTestDryRunOnly: { name: 'stryker.mutation_test.dry_run_only', attributes: {} },
  mutationTestEarlyResult: { name: 'stryker.mutation_test.early_result', attributes: {} },
  mutationTestNoTests: { name: 'stryker.mutation_test.no_tests', attributes: {} },
  mutationTestPhase: {
    name: 'mutationTest',
    attributes: {
      mutantCount: SpanAttributeCount,
      skippedMutantCount: SpanAttributeCount,
      testCount: SpanAttributeCount,
    },
  },
  mutationTestPlan: { name: 'stryker.mutation_test.plan', attributes: {} },
  mutationTestPlanMutants: { name: 'stryker.mutation_test.plan_mutants', attributes: {} },
  mutationTestPlanRead: { name: 'stryker.mutation_test.plan.read', attributes: {} },
  mutationTestReadRelativeFiles: { name: 'stryker.mutation_test.read_relative_files', attributes: {} },
  mutationTestSandboxFiles: { name: 'stryker.mutation_test.sandbox_files', attributes: {} },
  outputDrain: { name: 'stryker.output.drain', attributes: {} },
  outputModeProbe: { name: 'stryker.output_mode_probe', attributes: {} },
  outputModeProbeRead: { name: 'stryker.outputModeProbe.read', attributes: {} },
  phaseEntered: { name: 'stryker.phase.entered', attributes: {} },
  pluginLoadLoad: { name: 'stryker.plugin_load.load', attributes: {} },
  pluginLoadLoadPlugin: { name: 'stryker.plugin_load.load_plugin', attributes: {} },
  pluginLoadPackageEntrypoint: { name: 'stryker.plugin_load.package_entrypoint', attributes: {} },
  pluginLoadReport: { name: 'stryker.pluginLoad.report', attributes: {} },
  prepare: { name: 'stryker.prepare', attributes: {} },
  prepareAnnounceSummary: { name: 'stryker.prepare.announce-summary', attributes: {} },
  prepareApply: { name: 'stryker.prepare.apply', attributes: {} },
  prepareGather: { name: 'stryker.prepare.gather', attributes: {} },
  preparePhase: { name: 'prepare', attributes: {} },
  projectFilesRead: { name: 'stryker.project_files.read', attributes: {} },
  projectFilesWriteInto: { name: 'stryker.project_files.write-into', attributes: {} },
  projectRead: { name: 'stryker.project_read', attributes: {} },
  projectReadFromDisk: { name: 'stryker.project.read', attributes: {} },
  reportClearText: { name: 'stryker.report.clearText', attributes: {} },
  reportClearTextWrite: { name: 'stryker.report.clearText.write', attributes: {} },
  reportJson: { name: 'stryker.report.json', attributes: {} },
  reportJsonWrite: { name: 'stryker.report.json.write', attributes: {} },
  reportProgress: { name: 'stryker.report.progress', attributes: {} },
  reportProgressConsume: { name: 'stryker.report.progress.consume', attributes: {} },
  reportProgressConsumeEvent: { name: 'stryker.report.progress.consumeEvent', attributes: {} },
  reporterStreamAttach: { name: 'stryker.reporterStream.attach', attributes: {} },
  reporterStreamCloseStage: { name: 'stryker.reporterStream.closeStage', attributes: {} },
  reporterStreamCurrentReporterInit: { name: 'stryker.reporterStream.currentReporterInit', attributes: {} },
  reporterStreamDetach: { name: 'stryker.reporterStream.detach', attributes: {} },
  reporterStreamEnvironmentTraceInit: { name: 'stryker.reporterStream.environmentTraceInit', attributes: {} },
  reporterStreamOfferToChannel: { name: 'stryker.reporterStream.offerToChannel', attributes: {} },
  reporterStreamSettle: { name: 'stryker.reporterStream.settle', attributes: {} },
  reporterWiringSpawnPluginReporterFactory: {
    name: 'stryker.reporterWiring.spawnPluginReporterFactory',
    attributes: {},
  },
  restrictSocket: { name: 'restrictSocket', attributes: {} },
  rpcCapabilities: { name: 'rpc.capabilities', attributes: { 'rpc.method': SpanAttributeText } },
  rpcCheck: { name: 'rpc.check', attributes: { 'rpc.method': SpanAttributeText } },
  rpcClientCapabilities: { name: 'RpcClient.capabilities', attributes: {} },
  rpcClientCheck: { name: 'RpcClient.check', attributes: {} },
  rpcClientDryRun: { name: 'RpcClient.dryRun', attributes: {} },
  rpcClientFlush: { name: 'RpcClient.flush', attributes: {} },
  rpcClientGroup: { name: 'RpcClient.group', attributes: {} },
  rpcClientInit: { name: 'RpcClient.init', attributes: {} },
  rpcClientMutantRun: { name: 'RpcClient.mutantRun', attributes: {} },
  rpcClientOnEventBatch: { name: 'RpcClient.onEventBatch', attributes: {} },
  rpcDryRun: { name: 'rpc.dryRun', attributes: { 'rpc.method': SpanAttributeText } },
  rpcFlush: { name: 'rpc.flush', attributes: { 'rpc.method': SpanAttributeText } },
  rpcGroup: { name: 'rpc.group', attributes: { 'rpc.method': SpanAttributeText } },
  rpcInit: { name: 'rpc.init', attributes: { 'rpc.method': SpanAttributeText } },
  rpcMutantRun: { name: 'rpc.mutantRun', attributes: { 'rpc.method': SpanAttributeText } },
  rpcOnEventBatch: { name: 'rpc.onEventBatch', attributes: { 'rpc.method': SpanAttributeText } },
  rpcServerCapabilities: { name: 'RpcServer.capabilities', attributes: {} },
  rpcServerCheck: { name: 'RpcServer.check', attributes: {} },
  rpcServerDryRun: { name: 'RpcServer.dryRun', attributes: {} },
  rpcServerFlush: { name: 'RpcServer.flush', attributes: {} },
  rpcServerGroup: { name: 'RpcServer.group', attributes: {} },
  rpcServerInit: { name: 'RpcServer.init', attributes: {} },
  rpcServerMutantRun: { name: 'RpcServer.mutantRun', attributes: {} },
  rpcServerOnEventBatch: { name: 'RpcServer.onEventBatch', attributes: {} },
  runConclude: { name: 'stryker.run.conclude', attributes: {} },
  runConclusionRead: { name: 'stryker.run_conclusion.read', attributes: {} },
  runEventStreamCloseAndDrain: { name: 'stryker.runEventStream.closeAndDrain', attributes: {} },
  runEventStreamDrainFile: { name: 'stryker.runEventStream.drainFile', attributes: {} },
  runEventStreamDrainStoredFile: { name: 'stryker.runEventStream.drainStoredFile', attributes: {} },
  runEventStreamDrainToSinks: { name: 'stryker.runEventStream.drainToSinks', attributes: {} },
  runEventStreamEmitMachineModeOutput: { name: 'stryker.runEventStream.emitMachineModeOutput', attributes: {} },
  runEventStreamMake: { name: 'stryker.runEventStream.make', attributes: {} },
  runEventStreamNullScoreVerdict: { name: 'stryker.runEventStream.nullScoreVerdict', attributes: {} },
  runEventStreamOpen: { name: 'stryker.runEventStream.open', attributes: {} },
  runEventStreamOpenHeader: { name: 'stryker.runEventStream.openHeader', attributes: {} },
  runEventStreamStartDrain: { name: 'stryker.runEventStream.startDrain', attributes: {} },
  runEventStreamTick: { name: 'stryker.runEventStream.tick', attributes: {} },
  runRequest: { name: 'stryker.run_request', attributes: {} },
  runRequestGather: { name: 'stryker.run_request.gather', attributes: {} },
  sandboxAcquire: { name: 'stryker.sandbox.acquire', attributes: {} },
  sandboxBuildRun: { name: 'stryker.sandbox.build.run', attributes: {} },
  sandboxFindNodeModules: { name: 'stryker.sandbox.find_node_modules', attributes: {} },
  sandboxLinkNodeModules: { name: 'stryker.sandbox.link_node_modules', attributes: {} },
  sandboxMakeTempDir: { name: 'stryker.sandbox.make_temp_dir', attributes: {} },
  sandboxMoveDirectory: { name: 'stryker.sandbox.move_directory', attributes: {} },
  sandboxMoveDirectoryContents: { name: 'stryker.sandbox.move_directory.contents', attributes: {} },
  sandboxMoveEntry: { name: 'stryker.sandbox.move_entry', attributes: {} },
  sandboxPreprocessDisableTypeChecks: { name: 'stryker.sandbox.preprocess.disable_type_checks', attributes: {} },
  sandboxRemoveEmptyParent: { name: 'stryker.sandbox.remove_empty_parent', attributes: {} },
  sandboxRemoveTempDir: { name: 'stryker.sandbox.remove_temp_dir', attributes: {} },
  sandboxRestoreOriginal: { name: 'stryker.sandbox.restore_original', attributes: {} },
  sandboxSymlinkJunction: { name: 'stryker.sandbox.symlink_junction', attributes: {} },
  sandboxSymlinkNodeModules: { name: 'stryker.sandbox.symlink_node_modules', attributes: {} },
  sandboxTsconfigRewriteFileArrays: { name: 'stryker.sandbox.tsconfig.rewrite-file-arrays', attributes: {} },
  survivorsAdmission: { name: 'stryker.survivors_admission', attributes: {} },
  survivorsAdmissionGather: { name: 'stryker.survivors_admission.gather', attributes: {} },
  survivorsAdmissionHashSources: { name: 'stryker.survivors_admission.hash_sources', attributes: {} },
  survivorsAdmissionReadPriorReport: { name: 'stryker.survivors_admission.read_prior_report', attributes: {} },
  survivorsAdmissionReadSource: { name: 'stryker.survivors_admission.read_source', attributes: {} },
  survivorsAdmissionResolveOptions: { name: 'stryker.survivors_admission.resolve_options', attributes: {} },
  testRunnerApplyEnvironmentState: { name: 'stryker.testRunner.applyEnvironmentState', attributes: {} },
  testRunnerMaxReusePolicy: { name: 'stryker.testRunner.maxReusePolicy', attributes: {} },
  testRunnerMutantRun: {
    name: 'stryker.testRunner.mutantRun',
    attributes: {
      'stryker.mutant.file': Mutant.CanonicalFileName,
      'stryker.mutant.id': Mutant.MutantId,
      'stryker.mutant.mutator': Mutant.MutatorName,
      'stryker.mutant.status': Mutant.MutantStatusSchema,
    },
  },
  testRunnerReloadEnvironment: { name: 'stryker.testRunner.reloadEnvironment', attributes: {} },
  testRunnerWithEnvironmentReload: { name: 'stryker.testRunner.withEnvironmentReload', attributes: {} },
  testRunnerWithMaxReuse: { name: 'stryker.testRunner.withMaxReuse', attributes: {} },
  typescriptCheckerCheck: {
    name: 'typescript-checker.check',
    attributes: { 'stryker.mutants.count': SpanAttributeCount },
  },
  typescriptCheckerCheckMutants: { name: 'stryker.typescript_checker.check_mutants', attributes: {} },
  typescriptCheckerCompilerCheck: { name: 'typescript-checker.compiler.check', attributes: {} },
  typescriptCheckerCompilerClose: { name: 'typescript-checker.compiler.close', attributes: {} },
  typescriptCheckerCompilerDryRun: { name: 'typescript-checker.compiler.dryRun', attributes: {} },
  typescriptCheckerCompilerGroups: { name: 'typescript-checker.compiler.groups', attributes: {} },
  typescriptCheckerCompilerInit: { name: 'typescript-checker.compiler.init', attributes: {} },
  typescriptCheckerCompilerLineAndCharacter: { name: 'typescript-checker.compiler.lineAndCharacter', attributes: {} },
  typescriptCheckerCompilerMake: { name: 'typescript-checker.compiler.make', attributes: {} },
  typescriptCheckerCompilerNodes: { name: 'typescript-checker.compiler.nodes', attributes: {} },
  typescriptCheckerCompilerScoped: { name: 'typescript-checker.compiler.scoped', attributes: {} },
  typescriptCheckerRuntimeMakeChecker: { name: 'typescript-checker.runtime.makeChecker', attributes: {} },
  typescriptCheckerSoloRound: {
    name: 'typescript-checker.soloRound',
    attributes: { 'stryker.mutant.id': Mutant.MutantId },
  },
  validateOptions: { name: 'stryker.validate_options', attributes: {} },
  vitestMutantRun: { name: 'stryker.vitest.mutant_run', attributes: {} },
  vitestMutantRunRead: { name: 'vitest.mutant_run.read', attributes: {} },
  vitestRunnerCollectRaw: { name: 'vitest.runner.collect_raw', attributes: {} },
  vitestRunnerCompleteDryRun: { name: 'vitest.runner.complete_dry_run', attributes: {} },
  vitestRunnerCoverageOfFile: { name: 'vitest.runner.coverage_of_file', attributes: {} },
  vitestRunnerMake: { name: 'vitest.runner.make', attributes: {} },
  vitestRuntimeAcquire: { name: 'vitest.runtime.acquire', attributes: {} },
  vitestRuntimeApplyRunFilter: { name: 'vitest.runtime.apply_run_filter', attributes: {} },
  vitestRuntimeClose: { name: 'vitest.runtime.close', attributes: {} },
  vitestRuntimeOpen: { name: 'vitest.runtime.open', attributes: {} },
  vitestRuntimeReadSandboxSelfAliases: { name: 'vitest.runtime.read_sandbox_self_aliases', attributes: {} },
  vitestRuntimeStart: { name: 'vitest.runtime.start', attributes: {} },
  vitestStandbyPoolClaim: { name: 'vitest.standby_pool.claim', attributes: {} },
  vitestStandbyPoolDispose: { name: 'vitest.standby_pool.dispose', attributes: {} },
  vitestStandbyPoolMake: { name: 'vitest.standby_pool.make', attributes: {} },
  vitestStandbyPoolRelease: { name: 'vitest.standby_pool.release', attributes: {} },
  workerIdGeneratorMake: { name: 'stryker.worker.idGenerator.make', attributes: {} },
  workerProtocolFailInFlight: { name: 'stryker.worker.protocol.failInFlight', attributes: {} },
  workerProtocolMake: { name: 'stryker.worker.protocol.make', attributes: {} },
  workerSpawn: { name: 'stryker.worker.spawn', attributes: {} },
} as const satisfies Readonly<Record<string, SpanMember>>

export const spanMembers: ReadonlyArray<SpanMember> = Object.values(Spans)

const rpcServedSpans: ReadonlyMap<string, SpanMember> = new Map<string, SpanMember>([
  ['capabilities', Spans.rpcCapabilities],
  ['check', Spans.rpcCheck],
  ['dryRun', Spans.rpcDryRun],
  ['flush', Spans.rpcFlush],
  ['group', Spans.rpcGroup],
  ['init', Spans.rpcInit],
  ['mutantRun', Spans.rpcMutantRun],
  ['onEventBatch', Spans.rpcOnEventBatch],
])

export const rpcServedSpanOf = (method: string): SpanMember | undefined => rpcServedSpans.get(method)

if (import.meta.vitest !== void 0) {
  const { it } = await import('@systemfsoftware/vitest')

  it.prop(
    '∀m_ProtocolMethod_≡ServedByItsDeclaredRpcSpan',
    { of: [S.Literals(protocolMethods)], subject: rpcServedSpanOf },
    (subject, [drawn]) => subject(drawn)?.name === `rpc.${drawn}`,
  )
}
