const urlModule = globalThis.process.getBuiltinModule('node:url')
const fsModule = globalThis.process.getBuiltinModule('node:fs')
const pathModule = globalThis.process.getBuiltinModule('node:path')
const moduleBuiltin = globalThis.process.getBuiltinModule('node:module')

export const createRequire = moduleBuiltin.createRequire.bind(moduleBuiltin)
export const isBuiltin = moduleBuiltin.isBuiltin.bind(moduleBuiltin)
export const stripTypeScriptTypes = (code: string): string => moduleBuiltin.stripTypeScriptTypes(code)
export const readFileSync = (path: string): string => fsModule.readFileSync(path, 'utf8')
export const existsSync = fsModule.existsSync.bind(fsModule)
export const dirname = pathModule.dirname.bind(pathModule)
export const join = pathModule.join.bind(pathModule)
export const resolve = pathModule.resolve.bind(pathModule)

export const fileURLToPath = (url: string | URL): string => urlModule.fileURLToPath(url)
export const pathToFileURL = (path: string): URL => urlModule.pathToFileURL(path)
