allowBuilds:
  msgpackr-extract: false
  onnxruntime-node: false
  protobufjs: false
  sharp: false
catalog:
  "@commitlint/cli": ^21
  "@commitlint/config-conventional": ^21
  "@commitlint/types": ^21
  "@effect/platform-node": 4.0.0-rc.112
  "@effect/platform-node-shared": 4.0.0-rc.112
  "@effect/vitest": 4.0.0-rc.112
  "@microsoft/api-extractor": ^7
  "@noble/hashes": ^2
  "@oxc-parser/binding-wasm32-wasi": ^0.140.0
  "@oxc-project/types": ^0.140.0
  "@std/jsonc": jsr:^1
  "@systemfsoftware/all": ^2
  "@systemfsoftware/arethetypeswrong-cli": ^4
  "@systemfsoftware/effect-cell-types": ^8
  "@systemfsoftware/effect-gherkin-spec": ^4
  "@systemfsoftware/effect-schema-law": ^2
  "@systemfsoftware/effect-schema-vite": ^2
  "@systemfsoftware/oxlint-plugin": ^4
  "@systemfsoftware/oxlint-plugin-recommended": ^1
  "@systemfsoftware/tsconfig": ^1
  "@types/node": ^24
  "@vitest/browser-playwright": ^4
  "@vitest/coverage-v8": ^4
  fast-check: ^4
  effect: 4.0.0-rc.112
  husky: ^9
  lint-staged: ^17
  oxc-parser: ^0.140.0
  oxc-walker: ^1
  oxlint: ^1
  oxlint-tsgolint: ^7
  rimraf: ^6.1.3
  tsdown: ^0.23.0
  turbo: ^2
  type-fest: ^4
  typescript: ^7
  vitest: ^4
  concurrently: ^10
catalogMode: prefer
catalogs:
  stryker:
    mutation-testing-elements: 3.7.3
minimumReleaseAgeExclude:
  - "@systemfsoftware/*"
packages:
  - apps/*
  - packages/*
  - packages/toolchain/*
  - packages/ignorers/*
  - packages/frameworks/*
