import { type RunEvent, RunEventWireLine, S, type VerdictReached } from '@systemfsoftware/stryker-js'
import { normalizeCounts } from '../scripts/oracle/normalize.js'
import type { ExecResult } from './__fixtures__/container-environment.js'
import { type PreparedFixture, test } from './__fixtures__/container-harness.js'

// ORACLE-LITERALS:BEGIN — generated by `pnpm derive-oracle --reconcile`. Do not edit inside the markers.
const RESILIENCE_COUNTS: {
  readonly compileErrors: number
  readonly ignored: number
  readonly killedOrTimeout: number
  readonly noCoverage: number
  readonly pending: number
  readonly runtimeErrors: number
  readonly survived: number
} = {
  compileErrors: 14,
  ignored: 0,
  killedOrTimeout: 25,
  noCoverage: 0,
  pending: 0,
  runtimeErrors: 0,
  survived: 15,
}
// ORACLE-LITERALS:END

const ENTERPRISE_FIXTURE_URL = new URL('../testResources/enterprise-monorepo-fixture', import.meta.url)

const parseEventStream = (stdout: string): ReadonlyArray<RunEvent> =>
  stdout
    .split('\n')
    .map((line) => line.trim())
    .filter((line) => line.startsWith('{') && line.endsWith('}'))
    .map((line) => S.decodeUnknownSync(RunEventWireLine)(line))

const lastEvent = (events: ReadonlyArray<RunEvent>): RunEvent | undefined => events.at(-1)

test(
  'enterprise journey: runner resilience, worker process timeouts, and concurrency',
  { timeout: 900_000 },
  async ({ bdd, expect, prepareFixture }) => {
    let fixture: PreparedFixture
    let run: ExecResult
    let events: ReadonlyArray<RunEvent>
    let verdict: VerdictReached | undefined

    await bdd.given('an enterprise fixture in an isolated runner resilience container directory', async () => {
      fixture = await prepareFixture(ENTERPRISE_FIXTURE_URL, 'enterprise-resilience-fixture')
    })

    await bdd.when('the CLI executes with resilience and timeout configuration', async () => {
      run = await fixture.run(['run', 'stryker.resilience.config.ts'])
      events = parseEventStream(run.stdout)
      const terminal = lastEvent(events)
      if (terminal !== undefined && terminal._tag === 'verdict') {
        verdict = terminal
      }
    })

    await bdd.thenAssert(
      'the named trap is Timeout and clock counts are not pinned',
      () => {
        expect.soft(run.exitCode).toBe(0)
        expect.soft(verdict).toBeDefined()
        if (verdict === undefined) return

        const normalized = normalizeCounts(verdict.counts)
        expect.soft({
          compileErrors: normalized.compileErrors,
          ignored: normalized.ignored,
          noCoverage: normalized.noCoverage,
          pending: normalized.pending,
          runtimeErrors: normalized.runtimeErrors,
        }).toEqual({
          compileErrors: 0,
          ignored: RESILIENCE_COUNTS.ignored,
          noCoverage: RESILIENCE_COUNTS.noCoverage,
          pending: RESILIENCE_COUNTS.pending,
          runtimeErrors: RESILIENCE_COUNTS.runtimeErrors,
        })

        const reportedMutants = events.filter(
          (event): event is Extract<RunEvent, { _tag: 'mutant' }> => event._tag === 'mutant',
        )
        const trapTimeouts = reportedMutants.filter((mutant) =>
          mutant.status === 'Timeout' && mutant.file.includes('nontermination.ts')
        )
        expect.soft(trapTimeouts.length).toBeGreaterThan(0)
      },
    )
  },
)
