import { Gherkin, it, makeFeature, Then, When } from '@systemfsoftware/effect-gherkin-spec'
import type { RunEvent } from '@systemfsoftware/stryker-js'
import type { Check, Expect } from '@systemfsoftware/vitest'
import { Effect } from 'effect'
import {
  normalizeCounts,
  type NormalizedCounts,
  normalizeTally,
  withoutClockStatuses,
} from '../scripts/oracle/normalize.js'
import type { ExecResult } from '../src/Harness/guest-job.schema.js'
import { E2eHarnessLive, runStryker } from './__fixtures__/e2e-harness.fixture.js'
import { decodeStream } from './__fixtures__/machine-stream.fixture.js'

// ORACLE-LITERALS:BEGIN — generated by `pnpm derive-oracle --reconcile`. Do not edit inside the markers.
const EDGE_COUNTS: {
  readonly compileErrors: number
  readonly ignored: number
  readonly killedOrTimeout: number
  readonly noCoverage: number
  readonly pending: number
  readonly runtimeErrors: number
  readonly survived: number
} = {
  compileErrors: 5,
  ignored: 4,
  killedOrTimeout: 2,
  noCoverage: 0,
  pending: 0,
  runtimeErrors: 0,
  survived: 0,
}
const EDGE_MUTATOR_TALLY: Readonly<Record<string, number>> = {
  'ArithmeticOperator:KilledOrTimeout': 1,
  'ArrowFunction:CompileError': 1,
  'BlockStatement:CompileError': 2,
  'BlockStatement:KilledOrTimeout': 1,
  'ConditionalExpression:Ignored': 2,
  'EqualityOperator:Ignored': 2,
  'ObjectLiteral:CompileError': 1,
  'StringLiteral:CompileError': 1,
}
// ORACLE-LITERALS:END
const EDGE_TOTAL = Object.values(EDGE_COUNTS).reduce((sum, n) => sum + n, 0)

const ENTERPRISE_FIXTURE_URL = new URL('../testResources/enterprise-monorepo-fixture', import.meta.url)

const verdictOrUndefined = (
  events: ReadonlyArray<RunEvent.RunEvent>,
): RunEvent.VerdictReached | undefined => {
  const terminal = events.at(-1)
  return terminal !== undefined && terminal._tag === 'verdict' ? terminal : undefined
}

const tallyReported = (reported: ReadonlyArray<string>): Readonly<Record<string, number>> => {
  const tally: Record<string, number> = {}
  for (const key of reported) {
    tally[key] = (tally[key] ?? 0) + 1
  }
  return tally
}

const stripClockDimensions = (
  counts: NormalizedCounts,
): Omit<NormalizedCounts, 'killedOrTimeout' | 'survived'> => {
  const { killedOrTimeout: _killedOrTimeout, survived: _survived, ...exact } = counts
  return exact
}

const verifyEdgeOracle = (
  expect: Expect,
  run: ExecResult,
  events: ReadonlyArray<RunEvent.RunEvent>,
  verdict: RunEvent.VerdictReached | undefined,
): Check => {
  const normalized = verdict === undefined ? undefined : normalizeCounts(verdict.counts)
  const reported = events
    .filter((event): event is Extract<RunEvent.RunEvent, { _tag: 'mutantTested' }> => event._tag === 'mutantTested')
    .map((mutant) => `${mutant.mutatorName}:${mutant.status}`)

  return expect({
    exitCode: run.exitCode,
    verdictIsPresent: verdict !== undefined,
    breakThreshold: verdict?.thresholds.break,
    observedExact: normalized === undefined ? undefined : stripClockDimensions(normalized),
    reportedCount: reported.length,
    observedTally: withoutClockStatuses(normalizeTally(tallyReported(reported))),
  }).toStrictEqual({
    exitCode: 0,
    verdictIsPresent: true,
    breakThreshold: null,
    observedExact: stripClockDimensions(EDGE_COUNTS),
    reportedCount: EDGE_TOTAL,
    observedTally: withoutClockStatuses(EDGE_MUTATOR_TALLY),
  })
}

const Feature = makeFeature({ it })

Feature('Excluding mutators and ignoring mutants in an enterprise fixture', { timeout: 900_000 })
  .withLayer(E2eHarnessLive)
  .live(
    'boots a warm microVM for the enterprise fixture and runs the packed CLI, exporting host and worker spans to the Grafana LGTM collector',
  )
  .body(({ scenario }) => {
    scenario(
      'A run with excluded mutator configuration reports the authored edge-case oracle',
      Gherkin.Do.pipe(
        When('the CLI executes with excluded mutator configuration')(
          'run',
          () =>
            runStryker({
              fixture: ENTERPRISE_FIXTURE_URL,
              label: 'enterprise-edge-fixture',
              args: ['run', 'stryker.edge.config.ts'],
            }),
        ),
        When('the stdout event stream decodes to run events')(
          'events',
          (s) => decodeStream(s.run.output.result.stdout),
        ),
        When('the terminal verdict of the decoded stream is read')(
          'verdict',
          (s) => Effect.succeed(verdictOrUndefined(s.events)),
        ),
        Then('the verdict matches the authored mathematical oracle exactly')((s, expect) =>
          verifyEdgeOracle(expect, s.run.output.result, s.events, s.verdict)
        ),
      ),
    )
  })
