import { RunEvent } from '@systemfsoftware/stryker-js'
import { it } from '@systemfsoftware/vitest'
import type { Check, Expect } from '@systemfsoftware/vitest'
import { Effect } from 'effect'
import * as S from 'effect/Schema'
import {
  normalizeCounts,
  type NormalizedCounts,
  normalizeTally,
  withoutClockStatuses,
} from '../scripts/oracle/normalize.js'
import type { ExecResult } from '../src/Harness/guest-job.schema.js'
import { bddStep, prepareFixture } from './__fixtures__/microvm-harness.js'

// ORACLE-LITERALS:BEGIN — generated by `pnpm derive-oracle --reconcile`. Do not edit inside the markers.
const EDGE_COUNTS: {
  readonly compileErrors: number
  readonly ignored: number
  readonly killedOrTimeout: number
  readonly noCoverage: number
  readonly pending: number
  readonly runtimeErrors: number
  readonly survived: number
} = {
  compileErrors: 5,
  ignored: 4,
  killedOrTimeout: 2,
  noCoverage: 0,
  pending: 0,
  runtimeErrors: 0,
  survived: 0,
}
const EDGE_MUTATOR_TALLY: Readonly<Record<string, number>> = {
  'ArithmeticOperator:KilledOrTimeout': 1,
  'ArrowFunction:CompileError': 1,
  'BlockStatement:CompileError': 2,
  'BlockStatement:KilledOrTimeout': 1,
  'ConditionalExpression:Ignored': 2,
  'EqualityOperator:Ignored': 2,
  'ObjectLiteral:CompileError': 1,
  'StringLiteral:CompileError': 1,
}
// ORACLE-LITERALS:END
const EDGE_TOTAL = Object.values(EDGE_COUNTS).reduce((sum, n) => sum + n, 0)

const ENTERPRISE_FIXTURE_URL = new URL('../testResources/enterprise-monorepo-fixture', import.meta.url)

const parseEventStream = (stdout: string): ReadonlyArray<RunEvent.RunEvent> =>
  stdout
    .split('\n')
    .map((line) => line.trim())
    .filter((line) => line.startsWith('{') && line.endsWith('}'))
    .map((line) => S.decodeUnknownSync(RunEvent.RunEventWireLine)(line))

const tallyReported = (reported: ReadonlyArray<string>): Readonly<Record<string, number>> => {
  const tally: Record<string, number> = {}
  for (const key of reported) {
    tally[key] = (tally[key] ?? 0) + 1
  }
  return tally
}

const stripClockDimensions = (
  counts: NormalizedCounts,
): Omit<NormalizedCounts, 'killedOrTimeout' | 'survived'> => {
  const { killedOrTimeout: _killedOrTimeout, survived: _survived, ...exact } = counts
  return exact
}

const verifyEdgeOracle = (
  expect: Expect,
  run: ExecResult,
  events: ReadonlyArray<RunEvent.RunEvent>,
  verdict: RunEvent.VerdictReached | undefined,
): Check => {
  const normalized = verdict === undefined ? undefined : normalizeCounts(verdict.counts)
  const reported = events
    .filter((event): event is Extract<RunEvent.RunEvent, { _tag: 'mutantTested' }> => event._tag === 'mutantTested')
    .map((mutant) => `${mutant.mutatorName}:${mutant.status}`)

  return expect({
    exitCode: run.exitCode,
    verdictIsPresent: verdict !== undefined,
    breakThreshold: verdict?.thresholds.break,
    observedExact: normalized === undefined ? undefined : stripClockDimensions(normalized),
    reportedCount: reported.length,
    observedTally: withoutClockStatuses(normalizeTally(tallyReported(reported))),
  }).toStrictEqual({
    exitCode: 0,
    verdictIsPresent: true,
    breakThreshold: null,
    observedExact: stripClockDimensions(EDGE_COUNTS),
    reportedCount: EDGE_TOTAL,
    observedTally: withoutClockStatuses(EDGE_MUTATOR_TALLY),
  })
}

it.live(
  'enterprise journey: mutator exclusion filters and ignored mutants',
  function*({ expect }) {
    const fixture = yield* bddStep(
      'Given',
      'an enterprise fixture in an isolated edge cases container directory',
      prepareFixture(ENTERPRISE_FIXTURE_URL, 'enterprise-edge-fixture'),
    )
    const run = yield* bddStep(
      'When',
      'the CLI executes with excluded mutator configuration',
      Effect.promise(() => fixture.run(['run', 'stryker.edge.config.ts'])),
    )
    const events = parseEventStream(run.stdout)
    const terminal = events.at(-1)
    const verdict = terminal !== undefined && terminal._tag === 'verdict' ? terminal : undefined

    yield* bddStep(
      'Then',
      'the verdict matches the authored mathematical oracle exactly',
      verifyEdgeOracle(expect, run, events, verdict),
    )
  },
  { timeout: 900_000 },
)
