import { RunEvent } from '@systemfsoftware/stryker-js'
import { it } from '@systemfsoftware/vitest'
import type { Check, Expect } from '@systemfsoftware/vitest'
import { Effect } from 'effect'
import * as S from 'effect/Schema'
import {
  normalizeCounts,
  type NormalizedCounts,
  normalizeTally,
  withoutClockStatuses,
} from '../scripts/oracle/normalize.js'
import type { ExecResult } from '../src/Harness/guest-job.schema.js'
import { bddStep, prepareFixture } from './__fixtures__/microvm-harness.js'
import { pollWindowSpans, type TraceSpan } from './__fixtures__/tempo.js'

const SERVICE_NAME = process.env['OTEL_SERVICE_NAME'] ?? 'stryker-e2e'
const telemetryEnabled = process.env['OTEL_ENABLED'] === 'true'

const WORKER_SPAN_PREFIX = 'rpc.'

const CHECKER_SPAN_NAMES: ReadonlyArray<string> = ['rpc.check', 'rpc.group']

const HOST_PHASE_SPAN_NAMES: ReadonlyArray<string> = [
  'prepare',
  'instrument',
  'dryRun',
  'mutationTest',
  'mutationTest.batch',
]

const isWorkerSpan = (span: TraceSpan): boolean => span.name.startsWith(WORKER_SPAN_PREFIX)

const isCheckerSpan = (span: TraceSpan): boolean => CHECKER_SPAN_NAMES.includes(span.name)

const isHostPhaseSpan = (span: TraceSpan): boolean => HOST_PHASE_SPAN_NAMES.includes(span.name)

// ORACLE-LITERALS:BEGIN — generated by `pnpm derive-oracle --reconcile`. Do not edit inside the markers.
const LIFECYCLE_COUNTS: {
  readonly compileErrors: number
  readonly ignored: number
  readonly killedOrTimeout: number
  readonly noCoverage: number
  readonly pending: number
  readonly runtimeErrors: number
  readonly survived: number
} = {
  compileErrors: 98,
  ignored: 2,
  killedOrTimeout: 193,
  noCoverage: 0,
  pending: 0,
  runtimeErrors: 0,
  survived: 30,
}
const LIFECYCLE_MUTATOR_TALLY: Readonly<Record<string, number>> = {
  'ArithmeticOperator:KilledOrTimeout': 14,
  'ArrayDeclaration:CompileError': 1,
  'ArrayDeclaration:KilledOrTimeout': 2,
  'ArrowFunction:CompileError': 17,
  'ArrowFunction:KilledOrTimeout': 1,
  'AssignmentOperator:KilledOrTimeout': 4,
  'AssignmentOperator:Survived': 1,
  'BlockStatement:CompileError': 24,
  'BlockStatement:KilledOrTimeout': 31,
  'BlockStatement:Survived': 10,
  'BooleanLiteral:CompileError': 2,
  'BooleanLiteral:KilledOrTimeout': 12,
  'ConditionalExpression:CompileError': 11,
  'ConditionalExpression:Ignored': 2,
  'ConditionalExpression:KilledOrTimeout': 58,
  'ConditionalExpression:Survived': 9,
  'EqualityOperator:CompileError': 6,
  'EqualityOperator:KilledOrTimeout': 30,
  'EqualityOperator:Survived': 8,
  'LogicalOperator:CompileError': 9,
  'LogicalOperator:KilledOrTimeout': 5,
  'MethodExpression:CompileError': 1,
  'MethodExpression:KilledOrTimeout': 2,
  'MethodExpression:Survived': 1,
  'ObjectLiteral:CompileError': 15,
  'ObjectLiteral:KilledOrTimeout': 1,
  'OptionalChaining:CompileError': 6,
  'StringLiteral:CompileError': 6,
  'StringLiteral:KilledOrTimeout': 29,
  'StringLiteral:Survived': 1,
  'UpdateOperator:KilledOrTimeout': 4,
}
// ORACLE-LITERALS:END
const LIFECYCLE_TOTAL = Object.values(LIFECYCLE_COUNTS).reduce((sum, n) => sum + n, 0)

const ENTERPRISE_FIXTURE_URL = new URL('../testResources/enterprise-monorepo-fixture', import.meta.url)
const TERMINAL_RUN_KINDS: ReadonlyArray<string> = ['verdict', 'error', 'help']
const NON_TERMINAL_RUN_KINDS: ReadonlyArray<string> = [
  'stream',
  'phase',
  'plan',
  'mutantTested',
  'tick',
  'plugins',
  'formats',
  'skipped',
]
const REQUIRED_EVENT_KINDS: ReadonlyArray<string> = ['stream', 'phase', 'plan', 'mutantTested', 'verdict']
const ACTIONABLE_STATUSES: ReadonlyArray<string> = ['Survived', 'Timeout', 'NoCoverage', 'RuntimeError']
const ANSI_ESCAPE = new RegExp(`${String.fromCharCode(27)}\\[`)

const parseEventStream = (stdout: string): ReadonlyArray<RunEvent.RunEvent> =>
  stdout
    .split('\n')
    .map((line) => line.trim())
    .filter((line) => line.startsWith('{') && line.endsWith('}'))
    .map((line) => S.decodeUnknownSync(RunEvent.RunEventWireLine)(line))

const lastEvent = (events: ReadonlyArray<RunEvent.RunEvent>): RunEvent.RunEvent => {
  const event = events.at(-1)
  if (event === undefined) {
    throw new Error('stdout carries no events')
  }
  return event
}

const terminalIndexesIn = (kinds: ReadonlyArray<string>): ReadonlyArray<number> =>
  kinds
    .map((kind, index) => ({ index, kind }))
    .filter((entry) => TERMINAL_RUN_KINDS.includes(entry.kind))
    .map((entry) => entry.index)

const tallyReported = (reported: ReadonlyArray<string>): Readonly<Record<string, number>> => {
  const tally: Record<string, number> = {}
  for (const key of reported) {
    tally[key] = (tally[key] ?? 0) + 1
  }
  return tally
}

const tallySumOf = (tally: Readonly<Record<string, number>>): number =>
  Object.values(tally).reduce((sum, n) => sum + n, 0)

const stripClockDimensions = (
  counts: NormalizedCounts,
): Omit<NormalizedCounts, 'killedOrTimeout' | 'survived'> => {
  const { killedOrTimeout: _killedOrTimeout, survived: _survived, ...exact } = counts
  return exact
}

const countedSumOf = (counts: RunEvent.VerdictReached['counts']): number =>
  counts.killed +
  counts.survived +
  counts.compileErrors +
  counts.runtimeErrors +
  counts.timeout +
  counts.noCoverage +
  counts.ignored +
  counts.pending

const verifyStreamAndExit = (
  expect: Expect,
  run: ExecResult,
  events: ReadonlyArray<RunEvent.RunEvent>,
): Check => {
  const kinds: ReadonlyArray<string> = events.map((event) => event._tag)
  const preceding = kinds.slice(0, -1)

  return expect({
    exitCode: run.exitCode,
    terminalIndexes: terminalIndexesIn(kinds),
    lastKind: kinds.at(-1),
    ansiMatch: run.stdout.match(ANSI_ESCAPE),
    precedingIsNonEmpty: preceding.length > 0,
    strayPrecedingKinds: preceding.filter((kind) => !NON_TERMINAL_RUN_KINDS.includes(kind)),
    missingRequiredKinds: REQUIRED_EVENT_KINDS.filter((kind) => !kinds.includes(kind)),
  }).toStrictEqual({
    exitCode: 0,
    terminalIndexes: [kinds.length - 1],
    lastKind: 'verdict',
    ansiMatch: null,
    precedingIsNonEmpty: true,
    strayPrecedingKinds: [],
    missingRequiredKinds: [],
  })
}

const verifyOracleCounts = (expect: Expect, verdict: RunEvent.VerdictReached): Check =>
  expect({
    breakThreshold: verdict.thresholds.break,
    observedExact: stripClockDimensions(normalizeCounts(verdict.counts)),
  }).toStrictEqual({
    breakThreshold: null,
    observedExact: stripClockDimensions(LIFECYCLE_COUNTS),
  })

const verifyMutatorTallies = (
  expect: Expect,
  events: ReadonlyArray<RunEvent.RunEvent>,
  verdict: RunEvent.VerdictReached,
): Check => {
  const reported = events
    .filter((event): event is Extract<RunEvent.RunEvent, { _tag: 'mutantTested' }> => event._tag === 'mutantTested')
    .map((mutant) => `${mutant.mutatorName}:${mutant.status}`)
  const reportedTally = normalizeTally(tallyReported(reported))
  const envelopeActionable = verdict.counts.survived +
    verdict.counts.timeout +
    verdict.counts.noCoverage +
    verdict.counts.runtimeErrors

  return expect({
    reportedCount: reported.length,
    observedTally: withoutClockStatuses(reportedTally),
    reportedTallySum: tallySumOf(reportedTally),
    envelopeActionableCount: verdict.mutants.length,
    expectedActionableCount: envelopeActionable,
    unexpectedActionableStatuses: verdict.mutants
      .map((mutant) => mutant.status)
      .filter((status) => !ACTIONABLE_STATUSES.includes(status)),
    countsSum: countedSumOf(verdict.counts),
  }).toStrictEqual({
    reportedCount: LIFECYCLE_TOTAL,
    observedTally: withoutClockStatuses(LIFECYCLE_MUTATOR_TALLY),
    reportedTallySum: LIFECYCLE_TOTAL,
    envelopeActionableCount: envelopeActionable,
    expectedActionableCount: envelopeActionable,
    unexpectedActionableStatuses: [],
    countsSum: LIFECYCLE_TOTAL,
  })
}

const verifyRunIdConsistency = (
  expect: Expect,
  events: ReadonlyArray<RunEvent.RunEvent>,
  verdict: RunEvent.VerdictReached,
): Check => {
  const runIds = events
    .map((event) => ('runId' in event && typeof event.runId === 'string' ? String(event.runId) : undefined))
    .filter((runId): runId is string => runId !== undefined)

  return expect({
    carriesAtLeastTwoRunIds: runIds.length >= 2,
    distinctRunIds: new Set(runIds).size,
    verdictRunIdMatchesFirst: verdict.runId === runIds.at(0),
  }).toStrictEqual({
    carriesAtLeastTwoRunIds: true,
    distinctRunIds: 1,
    verdictRunIdMatchesFirst: true,
  })
}

interface PersistedMutant {
  readonly status: string
}

const verifyPersistedReport = (
  expect: Expect,
  reportText: string,
  verdict: RunEvent.VerdictReached,
): Check => {
  const report = JSON.parse(reportText) as {
    schemaVersion?: string
    files?: Record<string, { mutants?: Record<string, PersistedMutant> }>
  }
  const allReportedMutants = Object.values(report.files ?? {}).flatMap((file) => Object.values(file.mutants ?? {}))

  return expect({
    schemaVersion: report.schemaVersion,
    filesArePresent: report.files !== undefined,
    reportedMutantCount: allReportedMutants.length,
    killedInReport: allReportedMutants.filter((mutant) => mutant.status === 'Killed').length,
    survivedInReport: allReportedMutants.filter((mutant) => mutant.status === 'Survived').length,
    compileErrorsInReport: allReportedMutants.filter((mutant) => mutant.status === 'CompileError').length,
  }).toStrictEqual({
    schemaVersion: '1.0',
    filesArePresent: true,
    reportedMutantCount: LIFECYCLE_TOTAL,
    killedInReport: verdict.counts.killed,
    survivedInReport: verdict.counts.survived,
    compileErrorsInReport: verdict.counts.compileErrors,
  })
}

const verifyTracePropagation = (expect: Expect, spans: readonly TraceSpan[]): Check => {
  const workerTraceIds = new Set(spans.filter(isWorkerSpan).map((span) => span.traceId))
  const hostTraceIds = new Set(spans.filter(isHostPhaseSpan).map((span) => span.traceId))

  return expect({
    hostTraceIdsArePresent: hostTraceIds.size > 0,
    checkerSpanIsPresent: spans.some(isCheckerSpan),
    workerTraceIdsArePresent: workerTraceIds.size > 0,
    everyWorkerTraceIsHosted: [...workerTraceIds].every((traceId) => hostTraceIds.has(traceId)),
  }).toStrictEqual({
    hostTraceIdsArePresent: true,
    checkerSpanIsPresent: true,
    workerTraceIdsArePresent: true,
    everyWorkerTraceIsHosted: true,
  })
}

it.live(
  'enterprise journey: mutation lifecycle, modern syntax idioms, and report persistence',
  function*({ expect }) {
    const fixture = yield* bddStep(
      'Given',
      'an enterprise fixture in an isolated lifecycle container directory',
      prepareFixture(ENTERPRISE_FIXTURE_URL, 'enterprise-lifecycle-fixture'),
    )
    const startedSeconds = Math.floor(Date.now() / 1000) - 5
    const run = yield* bddStep(
      'When',
      'the CLI executes the full lifecycle mutation run',
      Effect.promise(() => fixture.run(['run'])),
    )
    const events = parseEventStream(run.stdout)
    const terminal = lastEvent(events)
    if (terminal._tag !== 'verdict') {
      throw new Error(`Expected terminal verdict event, received: ${terminal._tag}`)
    }

    yield* bddStep(
      'Then',
      'the process stream protocol invariants hold',
      verifyStreamAndExit(expect, run, events),
    )
    yield* bddStep(
      'And',
      'the verdict matches the mathematical oracle',
      verifyOracleCounts(expect, terminal),
    )
    yield* bddStep(
      'And',
      'the reported mutant tallies match the lifecycle oracle',
      verifyMutatorTallies(expect, events, terminal),
    )
    yield* bddStep(
      'And',
      'every event carries the verdict run id',
      verifyRunIdConsistency(expect, events, terminal),
    )
    yield* bddStep(
      'And',
      'persisted report JSON is saved to disk and matches the verdict counts',
      Effect.gen(function*() {
        const reportText = yield* Effect.promise(() => fixture.readFile('reports/mutation/mutation.json'))
        return yield* verifyPersistedReport(expect, reportText, terminal)
      }),
    )

    if (telemetryEnabled) {
      yield* bddStep(
        'And',
        'distributed telemetry spans propagate across execution',
        Effect.gen(function*() {
          const spans = yield* Effect.promise(() =>
            pollWindowSpans({
              startSeconds: startedSeconds,
              serviceName: SERVICE_NAME,
              isSettled: (seen) => seen.some(isWorkerSpan) && seen.some(isHostPhaseSpan),
            })
          )
          return yield* verifyTracePropagation(expect, spans)
        }),
      )
    }
  },
  { timeout: 2_400_000 },
)
