import { Gherkin, it, makeFeature, Then, When } from '@systemfsoftware/effect-gherkin-spec'
import type { RunEvent } from '@systemfsoftware/stryker-js'
import type { Check, Expect } from '@systemfsoftware/vitest'
import { Effect } from 'effect'
import {
  normalizeCounts,
  type NormalizedCounts,
  normalizeTally,
  withoutClockStatuses,
} from '../scripts/oracle/normalize.js'
import type { ExecResult } from '../src/Harness/guest-job.schema.js'
import { E2eHarnessLive, runStryker } from './__fixtures__/e2e-harness.fixture.js'
import { decodeStream } from './__fixtures__/machine-stream.fixture.js'

// ORACLE-LITERALS:BEGIN — generated by `pnpm derive-oracle --reconcile`. Do not edit inside the markers.
const CHECKER_COUNTS: {
  readonly compileErrors: number
  readonly ignored: number
  readonly killedOrTimeout: number
  readonly noCoverage: number
  readonly pending: number
  readonly runtimeErrors: number
  readonly survived: number
} = {
  compileErrors: 15,
  ignored: 0,
  killedOrTimeout: 12,
  noCoverage: 0,
  pending: 0,
  runtimeErrors: 0,
  survived: 0,
}
const CHECKER_MUTATOR_TALLY: Readonly<Record<string, number>> = {
  'ArrowFunction:CompileError': 4,
  'BlockStatement:CompileError': 2,
  'BlockStatement:KilledOrTimeout': 1,
  'BooleanLiteral:KilledOrTimeout': 1,
  'ConditionalExpression:CompileError': 3,
  'ConditionalExpression:KilledOrTimeout': 3,
  'EqualityOperator:CompileError': 1,
  'EqualityOperator:KilledOrTimeout': 2,
  'LogicalOperator:KilledOrTimeout': 1,
  'ObjectLiteral:CompileError': 1,
  'OptionalChaining:CompileError': 1,
  'StringLiteral:CompileError': 3,
  'StringLiteral:KilledOrTimeout': 4,
}
// ORACLE-LITERALS:END
const CHECKER_TOTAL = Object.values(CHECKER_COUNTS).reduce((sum, n) => sum + n, 0)

const ENTERPRISE_FIXTURE_URL = new URL('../testResources/enterprise-monorepo-fixture', import.meta.url)

const verdictOrUndefined = (
  events: ReadonlyArray<RunEvent.RunEvent>,
): RunEvent.VerdictReached | undefined => {
  const terminal = events.at(-1)
  return terminal !== undefined && terminal._tag === 'verdict' ? terminal : undefined
}

const tallyReported = (reported: ReadonlyArray<string>): Readonly<Record<string, number>> => {
  const tally: Record<string, number> = {}
  for (const key of reported) {
    tally[key] = (tally[key] ?? 0) + 1
  }
  return tally
}

const stripClockDimensions = (
  counts: NormalizedCounts,
): Omit<NormalizedCounts, 'killedOrTimeout' | 'survived'> => {
  const { killedOrTimeout: _killedOrTimeout, survived: _survived, ...exact } = counts
  return exact
}

const verifyCompositeCheckerOracle = (
  expect: Expect,
  run: ExecResult,
  events: ReadonlyArray<RunEvent.RunEvent>,
  verdict: RunEvent.VerdictReached | undefined,
): Check => {
  const normalized = verdict === undefined ? undefined : normalizeCounts(verdict.counts)
  const contractCompileErrors = events.filter(
    (event): event is Extract<RunEvent.RunEvent, { _tag: 'mutantTested' }> =>
      event._tag === 'mutantTested' && event.status === 'CompileError' && event.fileName.includes('contracts.ts'),
  )
  const reported = events
    .filter((event): event is Extract<RunEvent.RunEvent, { _tag: 'mutantTested' }> => event._tag === 'mutantTested')
    .map((mutant) => `${mutant.mutatorName}:${mutant.status}`)

  return expect({
    exitCode: run.exitCode,
    verdictIsPresent: verdict !== undefined,
    breakThreshold: verdict?.thresholds.break,
    observedExact: normalized === undefined ? undefined : stripClockDimensions(normalized),
    contractCompileErrorCount: contractCompileErrors.length,
    contractErrorsBelowTotal: contractCompileErrors.length < CHECKER_COUNTS.compileErrors,
    reportedCount: reported.length,
    observedTally: withoutClockStatuses(normalizeTally(tallyReported(reported))),
  }).toStrictEqual({
    exitCode: 0,
    verdictIsPresent: true,
    breakThreshold: null,
    observedExact: stripClockDimensions(CHECKER_COUNTS),
    contractCompileErrorCount: 5,
    contractErrorsBelowTotal: true,
    reportedCount: CHECKER_TOTAL,
    observedTally: withoutClockStatuses(CHECKER_MUTATOR_TALLY),
  })
}

const Feature = makeFeature({ it })

Feature('Checking project references and cross-package compile errors', { timeout: 900_000 })
  .withLayer(E2eHarnessLive)
  .live(
    'boots a warm microVM for the enterprise fixture and runs the packed CLI, exporting host and worker spans to the Grafana LGTM collector',
  )
  .body(({ scenario }) => {
    scenario(
      'A run with composite checker configuration reports the cross-package compile-error oracle',
      Gherkin.Do.pipe(
        When('the CLI executes with composite checker configuration')(
          'run',
          () =>
            runStryker({
              fixture: ENTERPRISE_FIXTURE_URL,
              label: 'enterprise-checker-fixture',
              args: ['run', 'stryker.checker.config.ts'],
            }),
        ),
        When('the stdout event stream decodes to run events')(
          'events',
          (s) => decodeStream(s.run.output.result.stdout),
        ),
        When('the terminal verdict of the decoded stream is read')(
          'verdict',
          (s) => Effect.succeed(verdictOrUndefined(s.events)),
        ),
        Then('the composite checker identifies downstream compilation errors matching oracle')((s, expect) =>
          verifyCompositeCheckerOracle(expect, s.run.output.result, s.events, s.verdict)
        ),
      ),
    )
  })
