import { RunEvent } from '@systemfsoftware/stryker-js'
import { it } from '@systemfsoftware/vitest'
import type { Check, Expect } from '@systemfsoftware/vitest'
import { Effect } from 'effect'
import * as S from 'effect/Schema'
import { normalizeCounts } from '../scripts/oracle/normalize.js'
import type { ExecResult } from '../src/Harness/guest-job.schema.js'
import { bddStep, prepareFixture } from './__fixtures__/microvm-harness.js'

// ORACLE-LITERALS:BEGIN — generated by `pnpm derive-oracle --reconcile`. Do not edit inside the markers.
const RESILIENCE_COUNTS: {
  readonly compileErrors: number
  readonly ignored: number
  readonly killedOrTimeout: number
  readonly noCoverage: number
  readonly pending: number
  readonly runtimeErrors: number
  readonly survived: number
} = {
  compileErrors: 14,
  ignored: 0,
  killedOrTimeout: 25,
  noCoverage: 0,
  pending: 0,
  runtimeErrors: 0,
  survived: 15,
}
// ORACLE-LITERALS:END

const ENTERPRISE_FIXTURE_URL = new URL('../testResources/enterprise-monorepo-fixture', import.meta.url)

const parseEventStream = (stdout: string): ReadonlyArray<RunEvent.RunEvent> =>
  stdout
    .split('\n')
    .map((line) => line.trim())
    .filter((line) => line.startsWith('{') && line.endsWith('}'))
    .map((line) => S.decodeUnknownSync(RunEvent.RunEventWireLine)(line))

const verifyResilienceCounts = (
  expect: Expect,
  run: ExecResult,
  events: ReadonlyArray<RunEvent.RunEvent>,
  verdict: RunEvent.VerdictReached | undefined,
): Check => {
  const normalized = verdict === undefined ? undefined : normalizeCounts(verdict.counts)
  const timeouts = events
    .filter((event): event is Extract<RunEvent.RunEvent, { _tag: 'mutantTested' }> => event._tag === 'mutantTested')
    .filter((mutant) => mutant.status === 'Timeout')
  const trapTimeouts = timeouts.filter((mutant) => mutant.fileName.includes('nontermination.ts'))

  return expect({
    exitCode: run.exitCode,
    verdictIsPresent: verdict !== undefined,
    ignored: normalized?.ignored,
    noCoverage: normalized?.noCoverage,
    pending: normalized?.pending,
    runtimeErrors: normalized?.runtimeErrors,
    trapTimeoutsAreReported: trapTimeouts.length > 0,
    everyTimeoutIsATrap: timeouts.length === trapTimeouts.length,
  }).toStrictEqual({
    exitCode: 0,
    verdictIsPresent: true,
    ignored: RESILIENCE_COUNTS.ignored,
    noCoverage: RESILIENCE_COUNTS.noCoverage,
    pending: RESILIENCE_COUNTS.pending,
    runtimeErrors: RESILIENCE_COUNTS.runtimeErrors,
    trapTimeoutsAreReported: true,
    everyTimeoutIsATrap: true,
  })
}

it.live(
  'enterprise journey: runner resilience, worker process timeouts, and concurrency',
  function*({ expect }) {
    const fixture = yield* bddStep(
      'Given',
      'an enterprise fixture in an isolated runner resilience container directory',
      prepareFixture(ENTERPRISE_FIXTURE_URL, 'enterprise-resilience-fixture'),
    )
    const run = yield* bddStep(
      'When',
      'the CLI executes with resilience and timeout configuration',
      Effect.promise(() => fixture.run(['run', 'stryker.resilience.config.ts'])),
    )
    const events = parseEventStream(run.stdout)
    const terminal = events.at(-1)
    const verdict = terminal !== undefined && terminal._tag === 'verdict' ? terminal : undefined

    yield* bddStep(
      'Then',
      'the named trap is Timeout and clock counts are not pinned',
      verifyResilienceCounts(expect, run, events, verdict),
    )
  },
  { timeout: 900_000 },
)
