import { type RunEvent, RunEventWireLine, S, type VerdictReached } from '@systemfsoftware/stryker-js'
import { normalizeCounts, normalizeTally } from '../scripts/oracle/normalize.js'
import type { ExecResult } from './__fixtures__/container-environment.js'
import { type PreparedFixture, test } from './__fixtures__/container-harness.js'

// ORACLE-LITERALS:BEGIN — generated by `pnpm derive-oracle --reconcile`. Do not edit inside the markers.
const CHECKER_COUNTS: {
  readonly compileErrors: number
  readonly ignored: number
  readonly killedOrTimeout: number
  readonly noCoverage: number
  readonly pending: number
  readonly runtimeErrors: number
  readonly survived: number
} = {
  compileErrors: 15,
  ignored: 0,
  killedOrTimeout: 12,
  noCoverage: 0,
  pending: 0,
  runtimeErrors: 0,
  survived: 0,
}
const CHECKER_MUTATOR_TALLY: Readonly<Record<string, number>> = {
  'ArrowFunction:CompileError': 4,
  'BlockStatement:CompileError': 2,
  'BlockStatement:KilledOrTimeout': 1,
  'BooleanLiteral:KilledOrTimeout': 1,
  'ConditionalExpression:CompileError': 3,
  'ConditionalExpression:KilledOrTimeout': 3,
  'EqualityOperator:CompileError': 1,
  'EqualityOperator:KilledOrTimeout': 2,
  'LogicalOperator:KilledOrTimeout': 1,
  'ObjectLiteral:CompileError': 1,
  'OptionalChaining:CompileError': 1,
  'StringLiteral:CompileError': 3,
  'StringLiteral:KilledOrTimeout': 4,
}
// ORACLE-LITERALS:END
const CHECKER_TOTAL = Object.values(CHECKER_COUNTS).reduce((sum, n) => sum + n, 0)

const ENTERPRISE_FIXTURE_URL = new URL('../testResources/enterprise-monorepo-fixture', import.meta.url)

const parseEventStream = (stdout: string): ReadonlyArray<RunEvent> =>
  stdout
    .split('\n')
    .map((line) => line.trim())
    .filter((line) => line.startsWith('{') && line.endsWith('}'))
    .map((line) => S.decodeUnknownSync(RunEventWireLine)(line))

const lastEvent = (events: ReadonlyArray<RunEvent>): RunEvent | undefined => events.at(-1)

const tallyReported = (reported: ReadonlyArray<string>): Readonly<Record<string, number>> => {
  const tally: Record<string, number> = {}
  for (const key of reported) {
    tally[key] = (tally[key] ?? 0) + 1
  }
  return tally
}

test(
  'enterprise journey: TypeScript composite checker project references and cross-package compile errors',
  { timeout: 900_000 },
  async ({ bdd, expect, prepareFixture }) => {
    let fixture: PreparedFixture
    let run: ExecResult
    let events: ReadonlyArray<RunEvent>
    let verdict: VerdictReached | undefined

    await bdd.given('an enterprise fixture in an isolated composite checker container directory', async () => {
      fixture = await prepareFixture(ENTERPRISE_FIXTURE_URL, 'enterprise-checker-fixture')
    })

    await bdd.when('the CLI executes with composite checker configuration', async () => {
      run = await fixture.run(['run', 'stryker.checker.config.ts'])
      events = parseEventStream(run.stdout)
      const terminal = lastEvent(events)
      if (terminal !== undefined && terminal._tag === 'verdict') {
        verdict = terminal
      }
    })

    await bdd.thenAssert('the composite checker identifies downstream compilation errors matching oracle', () => {
      expect.soft(run.exitCode).toBe(0)
      expect.soft(verdict).toBeDefined()
      if (verdict === undefined) return

      expect.soft(verdict.thresholds.break).toBeNull()
      expect.soft(normalizeCounts(verdict.counts)).toEqual(CHECKER_COUNTS)

      const contractCompileErrors = events.filter(
        (e): e is Extract<RunEvent, { _tag: 'mutant' }> =>
          e._tag === 'mutant' && e.status === 'CompileError' && e.file.includes('contracts.ts'),
      )
      expect.soft(contractCompileErrors.length).toBe(5)
      expect.soft(contractCompileErrors.length).toBeLessThan(CHECKER_COUNTS.compileErrors)

      const reported = events
        .filter((event): event is Extract<RunEvent, { _tag: 'mutant' }> => event._tag === 'mutant')
        .map((m) => `${m.mutator}:${m.status}`)

      expect.soft(reported).toHaveLength(CHECKER_TOTAL)
      const reportedTally = normalizeTally(tallyReported(reported))
      expect.soft(reportedTally).toEqual(CHECKER_MUTATOR_TALLY)
    })
  },
)
