import { Gherkin, it, makeFeature, Then, When } from '@systemfsoftware/effect-gherkin-spec'
import type { RunEvent } from '@systemfsoftware/stryker-js'
import { Contract } from '@systemfsoftware/trace-spec'
import type { Check, Expect } from '@systemfsoftware/vitest'
import { Effect } from 'effect'

import {
  normalizeCounts,
  type NormalizedCounts,
  normalizeTally,
  withoutClockStatuses,
} from '../scripts/oracle/normalize.js'
import type { ExecResult } from '../src/Harness/guest-job.schema.js'
import { E2eHarnessLive } from './__fixtures__/e2e-harness.fixture.js'
import { decodeStream, reportedMutantsOf, runIdsIn, verdictEvent } from './__fixtures__/machine-stream.fixture.js'
import { strykerLifecycleContract } from './__fixtures__/stryker-trace.fixture.js'
import { TraceObservationLive } from './__fixtures__/trace-observation.fixture.js'

// ORACLE-LITERALS:BEGIN — generated by `pnpm derive-oracle --reconcile`. Do not edit inside the markers.
const LIFECYCLE_COUNTS: {
  readonly compileErrors: number
  readonly ignored: number
  readonly killedOrTimeout: number
  readonly noCoverage: number
  readonly pending: number
  readonly runtimeErrors: number
  readonly survived: number
} = {
  compileErrors: 98,
  ignored: 2,
  killedOrTimeout: 193,
  noCoverage: 0,
  pending: 0,
  runtimeErrors: 0,
  survived: 30,
}
const LIFECYCLE_MUTATOR_TALLY: Readonly<Record<string, number>> = {
  'ArithmeticOperator:KilledOrTimeout': 14,
  'ArrayDeclaration:CompileError': 1,
  'ArrayDeclaration:KilledOrTimeout': 2,
  'ArrowFunction:CompileError': 17,
  'ArrowFunction:KilledOrTimeout': 1,
  'AssignmentOperator:KilledOrTimeout': 4,
  'AssignmentOperator:Survived': 1,
  'BlockStatement:CompileError': 24,
  'BlockStatement:KilledOrTimeout': 31,
  'BlockStatement:Survived': 10,
  'BooleanLiteral:CompileError': 2,
  'BooleanLiteral:KilledOrTimeout': 12,
  'ConditionalExpression:CompileError': 11,
  'ConditionalExpression:Ignored': 2,
  'ConditionalExpression:KilledOrTimeout': 58,
  'ConditionalExpression:Survived': 9,
  'EqualityOperator:CompileError': 6,
  'EqualityOperator:KilledOrTimeout': 30,
  'EqualityOperator:Survived': 8,
  'LogicalOperator:CompileError': 9,
  'LogicalOperator:KilledOrTimeout': 5,
  'MethodExpression:CompileError': 1,
  'MethodExpression:KilledOrTimeout': 2,
  'MethodExpression:Survived': 1,
  'ObjectLiteral:CompileError': 15,
  'ObjectLiteral:KilledOrTimeout': 1,
  'OptionalChaining:CompileError': 6,
  'StringLiteral:CompileError': 6,
  'StringLiteral:KilledOrTimeout': 29,
  'StringLiteral:Survived': 1,
  'UpdateOperator:KilledOrTimeout': 4,
}
// ORACLE-LITERALS:END
const LIFECYCLE_TOTAL = Object.values(LIFECYCLE_COUNTS).reduce((sum, n) => sum + n, 0)

const ENTERPRISE_FIXTURE_URL = new URL('../testResources/enterprise-monorepo-fixture', import.meta.url)
const ENTERPRISE_FIXTURE_LABEL = 'enterprise-lifecycle-fixture'
const PERSISTED_REPORT_PATH = 'reports/mutation/mutation.json'
const LIFECYCLE_TIMEOUT_MILLIS = 2_400_000
const TERMINAL_RUN_KINDS: ReadonlyArray<string> = ['verdict', 'error', 'help']
const NON_TERMINAL_RUN_KINDS: ReadonlyArray<string> = [
  'stream',
  'phase',
  'plan',
  'mutantTested',
  'tick',
  'plugins',
  'formats',
  'skipped',
]
const REQUIRED_EVENT_KINDS: ReadonlyArray<string> = ['stream', 'phase', 'plan', 'mutantTested', 'verdict']
const ACTIONABLE_STATUSES: ReadonlyArray<string> = ['Survived', 'Timeout', 'NoCoverage', 'RuntimeError']
const ANSI_ESCAPE = new RegExp(`${String.fromCharCode(27)}\\[`)

const terminalIndexesIn = (kinds: ReadonlyArray<string>): ReadonlyArray<number> =>
  kinds
    .map((kind, index) => ({ index, kind }))
    .filter((entry) => TERMINAL_RUN_KINDS.includes(entry.kind))
    .map((entry) => entry.index)

const tallyReported = (reported: ReadonlyArray<string>): Readonly<Record<string, number>> => {
  const tally: Record<string, number> = {}
  for (const key of reported) {
    tally[key] = (tally[key] ?? 0) + 1
  }
  return tally
}

const tallySumOf = (tally: Readonly<Record<string, number>>): number =>
  Object.values(tally).reduce((sum, n) => sum + n, 0)

const stripClockDimensions = (
  counts: NormalizedCounts,
): Omit<NormalizedCounts, 'killedOrTimeout' | 'survived'> => {
  const { killedOrTimeout: _killedOrTimeout, survived: _survived, ...exact } = counts
  return exact
}

const countedSumOf = (counts: RunEvent.VerdictReached['counts']): number =>
  counts.killed +
  counts.survived +
  counts.compileErrors +
  counts.runtimeErrors +
  counts.timeout +
  counts.noCoverage +
  counts.ignored +
  counts.pending

const verifyStreamAndExit = (
  expect: Expect,
  run: ExecResult,
  events: ReadonlyArray<RunEvent.RunEvent>,
): Check => {
  const kinds: ReadonlyArray<string> = events.map((event) => event._tag)
  const preceding = kinds.slice(0, -1)

  return expect({
    exitCode: run.exitCode,
    terminalIndexes: terminalIndexesIn(kinds),
    lastKind: kinds.at(-1),
    ansiMatch: run.stdout.match(ANSI_ESCAPE),
    precedingIsNonEmpty: preceding.length > 0,
    strayPrecedingKinds: preceding.filter((kind) => !NON_TERMINAL_RUN_KINDS.includes(kind)),
    missingRequiredKinds: REQUIRED_EVENT_KINDS.filter((kind) => !kinds.includes(kind)),
  }).toStrictEqual({
    exitCode: 0,
    terminalIndexes: [kinds.length - 1],
    lastKind: 'verdict',
    ansiMatch: null,
    precedingIsNonEmpty: true,
    strayPrecedingKinds: [],
    missingRequiredKinds: [],
  })
}

const verifyOracleCounts = (expect: Expect, verdict: RunEvent.VerdictReached): Check =>
  expect({
    breakThreshold: verdict.thresholds.break,
    observedExact: stripClockDimensions(normalizeCounts(verdict.counts)),
  }).toStrictEqual({
    breakThreshold: null,
    observedExact: stripClockDimensions(LIFECYCLE_COUNTS),
  })

const verifyMutatorTallies = (
  expect: Expect,
  reported: ReadonlyArray<string>,
  verdict: RunEvent.VerdictReached,
): Check => {
  const reportedTally = normalizeTally(tallyReported(reported))
  const envelopeActionable = verdict.counts.survived +
    verdict.counts.timeout +
    verdict.counts.noCoverage +
    verdict.counts.runtimeErrors

  return expect({
    reportedCount: reported.length,
    observedTally: withoutClockStatuses(reportedTally),
    reportedTallySum: tallySumOf(reportedTally),
    envelopeActionableCount: verdict.mutants.length,
    expectedActionableCount: envelopeActionable,
    unexpectedActionableStatuses: verdict.mutants
      .map((mutant) => mutant.status)
      .filter((status) => !ACTIONABLE_STATUSES.includes(status)),
    countsSum: countedSumOf(verdict.counts),
  }).toStrictEqual({
    reportedCount: LIFECYCLE_TOTAL,
    observedTally: withoutClockStatuses(LIFECYCLE_MUTATOR_TALLY),
    reportedTallySum: LIFECYCLE_TOTAL,
    envelopeActionableCount: envelopeActionable,
    expectedActionableCount: envelopeActionable,
    unexpectedActionableStatuses: [],
    countsSum: LIFECYCLE_TOTAL,
  })
}

const verifyRunIdConsistency = (
  expect: Expect,
  runIds: ReadonlyArray<string>,
  verdict: RunEvent.VerdictReached,
): Check =>
  expect({
    carriesAtLeastTwoRunIds: runIds.length >= 2,
    distinctRunIds: new Set(runIds).size,
    verdictRunIdMatchesFirst: verdict.runId === runIds.at(0),
  }).toStrictEqual({
    carriesAtLeastTwoRunIds: true,
    distinctRunIds: 1,
    verdictRunIdMatchesFirst: true,
  })

interface PersistedMutant {
  readonly status: string
}

const verifyPersistedReport = (
  expect: Expect,
  reportText: string,
  verdict: RunEvent.VerdictReached,
): Check => {
  const report = JSON.parse(reportText) as {
    schemaVersion?: string
    files?: Record<string, { mutants?: Record<string, PersistedMutant> }>
  }
  const allReportedMutants = Object.values(report.files ?? {}).flatMap((file) => Object.values(file.mutants ?? {}))

  return expect({
    schemaVersion: report.schemaVersion,
    filesArePresent: report.files !== undefined,
    reportedMutantCount: allReportedMutants.length,
    killedInReport: allReportedMutants.filter((mutant) => mutant.status === 'Killed').length,
    survivedInReport: allReportedMutants.filter((mutant) => mutant.status === 'Survived').length,
    compileErrorsInReport: allReportedMutants.filter((mutant) => mutant.status === 'CompileError').length,
  }).toStrictEqual({
    schemaVersion: '1.0',
    filesArePresent: true,
    reportedMutantCount: LIFECYCLE_TOTAL,
    killedInReport: verdict.counts.killed,
    survivedInReport: verdict.counts.survived,
    compileErrorsInReport: verdict.counts.compileErrors,
  })
}

const Feature = makeFeature({ it })

Feature('Running the enterprise mutation lifecycle through the packed CLI', { timeout: LIFECYCLE_TIMEOUT_MILLIS })
  .withLayer(E2eHarnessLive)
  .withScenarioLayer(TraceObservationLive)
  .live(
    'boots a warm microVM for the enterprise fixture and runs the packed CLI, whose host and worker spans the Grafana LGTM collector holds under the owned trace id of the run',
  )
  .body(({ scenario }) => {
    scenario(
      'The lifecycle run holds its trace contract and matches the enterprise oracle',
      Gherkin.Do.pipe(
        When('the CLI executes the full lifecycle mutation run and the trace contract is judged')(
          'judgment',
          () =>
            Contract.judge(strykerLifecycleContract, {
              fixture: ENTERPRISE_FIXTURE_URL,
              label: ENTERPRISE_FIXTURE_LABEL,
              args: ['run'],
            }),
        ),
        Then('the trace of the run holds the lifecycle contract')((s, expect) =>
          Contract.verdictCheck(strykerLifecycleContract, expect, s.judgment)
        ),
        When('the stdout event stream decodes to run events')(
          'events',
          (s) => decodeStream(s.judgment.run.output.result.stdout),
        ),
        Then('the process stream protocol invariants hold')((s, expect) =>
          verifyStreamAndExit(expect, s.judgment.run.output.result, s.events)
        ),
        When('the terminal verdict of the decoded stream is read')(
          'verdict',
          (s) => verdictEvent(s.events),
        ),
        Then('the verdict matches the mathematical oracle')((s, expect) => verifyOracleCounts(expect, s.verdict)),
        When('the reported mutants of the decoded stream are read')(
          'reported',
          (s) => Effect.succeed(reportedMutantsOf(s.events)),
        ),
        Then('the reported mutant tallies match the lifecycle oracle')((s, expect) =>
          verifyMutatorTallies(expect, s.reported, s.verdict)
        ),
        When('the run ids carried by the decoded stream are read')(
          'runIds',
          (s) => Effect.succeed(runIdsIn(s.events)),
        ),
        Then('every event carries the verdict run id')((s, expect) =>
          verifyRunIdConsistency(expect, s.runIds, s.verdict)
        ),
        When('the persisted report of the run is read from its fork')(
          'report',
          (s) => s.judgment.run.output.readFile(PERSISTED_REPORT_PATH),
        ),
        Then('the persisted report matches the verdict counts')((s, expect) =>
          verifyPersistedReport(expect, s.report, s.verdict)
        ),
      ),
    )
  })
