import type { BaselineCounts } from './baseline.js'

export const BLOCK_BEGIN =
  '// ORACLE-LITERALS:BEGIN — generated by `pnpm derive-oracle --reconcile`. Do not edit inside the markers.'
export const BLOCK_END = '// ORACLE-LITERALS:END'

export interface JourneyLiterals {
  readonly prefix: string
  readonly counts: BaselineCounts
  readonly mutatorStatusTally: Readonly<Record<string, number>>
}

const COUNT_KEY_ORDER: ReadonlyArray<keyof BaselineCounts> = [
  'compileErrors',
  'ignored',
  'killed',
  'noCoverage',
  'pending',
  'runtimeErrors',
  'survived',
  'timeout',
]

function renderCounts(counts: BaselineCounts): string {
  const lines = COUNT_KEY_ORDER.map((key) => `  ${key}: ${counts[key]},`)
  return `{\n${lines.join('\n')}\n}`
}

function renderTally(tally: Readonly<Record<string, number>>): string {
  const keys = Object.keys(tally).sort()
  if (keys.length === 0) return '{}'
  const lines = keys.map((key) => `  '${key}': ${tally[key]},`)
  return `{\n${lines.join('\n')}\n}`
}

const COUNTS_TYPE_LINES = [
  '  readonly compileErrors: number',
  '  readonly ignored: number',
  '  readonly killed: number',
  '  readonly noCoverage: number',
  '  readonly pending: number',
  '  readonly runtimeErrors: number',
  '  readonly survived: number',
  '  readonly timeout: number',
].join('\n')

export function renderLiteralBlock(literals: JourneyLiterals): string {
  const parts = [BLOCK_BEGIN]
  parts.push(`const ${literals.prefix}_COUNTS: {\n${COUNTS_TYPE_LINES}\n} = ${renderCounts(literals.counts)}`)
  if (Object.keys(literals.mutatorStatusTally).length > 0) {
    parts.push(
      `const ${literals.prefix}_MUTATOR_TALLY: Readonly<Record<string, number>> = ${
        renderTally(literals.mutatorStatusTally)
      }`,
    )
  }
  parts.push(BLOCK_END)
  return parts.join('\n')
}

export function extractLiteralBlock(fileText: string): string | undefined {
  const begin = fileText.indexOf(BLOCK_BEGIN)
  if (begin < 0) return undefined
  const end = fileText.indexOf(BLOCK_END, begin)
  if (end < 0) return undefined
  return fileText.slice(begin, end + BLOCK_END.length)
}

export function spliceLiteralBlock(fileText: string, block: string): string {
  const existing = extractLiteralBlock(fileText)
  if (existing === undefined) {
    throw new Error('Journey file has no ORACLE-LITERALS region; add the markers before reconciling')
  }
  return fileText.replace(existing, block)
}
