export {
  DrainCompleted,
  type DrainedStatus,
  type DrainedTest,
  DrainedTestSchema,
  type DrainOutcome,
  drainRegistry as pureDrainRegistry,
  DrainRegistryCommand,
  DrainTimedOut,
  type TestOutcome,
  TestOutcomeSchema,
} from './core/drain-registry.workflow.js'
export {
  createHarnessApi,
  createRegistry,
  DEFAULT_TITLE_VALUE_FORMAT_TRUNCATE,
  defaultFormatValue,
  defaultSnapshotPath,
  type EachValueFormatter,
  formatEachName,
  guardedExpect,
  guardedVi,
  type HarnessApi,
  harnessSourceFor,
  type HarnessTestContext,
  harnessUrlForSpecifier,
  hooksFor,
  SNAPSHOT_DIRECTORY,
  SNAPSHOT_SUFFIX,
  type SnapshotTask,
  snapshotTaskOf,
  type SnapshotTest,
  type SnapshotUpdateMode,
  snapshotUpdateMode,
  STATE_KEY,
  suiteHooksFor,
  type TestRegistry,
} from './core/index.js'
export { decideTestStatus, type TestStatusDecision } from './core/test-status.js'
export {
  type VmAlias,
  type VmAliasFind,
  VmAliasFindSchema,
  VmAliasSchema,
  type VmExpectConfig,
  VmExpectConfigSchema,
  VmProjectConfigSchema,
  type VmTagDefinition,
  VmTagDefinitionSchema,
  VmVitestConfigSchema,
} from './core/vitest-config.schema.js'
export {
  type VmMutantCoverage,
  VmMutantCoverageSchema,
  type VmRunKind,
  VmRunKindSchema,
  type VmRunRequest,
  VmRunRequestSchema,
  type VmRunResponse,
  VmRunResponseSchema,
  type VmSessionOptions,
  VmSessionOptionsSchema,
  type VmTestResult,
  VmTestResultSchema,
  type VmTestStatus,
  VmTestStatusSchema,
  type VmWorkerRequest,
  VmWorkerRequestSchema,
  type VmWorkerResponse,
  VmWorkerResponseSchema,
} from './core/vm-protocol.schema.js'
export {
  activateSandbox,
  builtinPlugins,
  createMockingPlugin,
  createSnapshotEnvironment,
  createSnapshotSupport,
  createVmSession,
  createVmWorkerClient,
  deactivateSandbox,
  definePlugin,
  ensureVitestWorkerState,
  environmentPlugin,
  executeDrainRegistry,
  executeDrainRegistry as drainRegistry,
  globalsPlugin,
  installInterception,
  makeEffectMethods,
  nativeImport,
  readGlobalState,
  runnerStatePlugin,
  setupFilesPlugin,
  setWorkerTestFile,
  snapshotClientOf,
  snapshotsPlugin,
  uninstallInterception,
  VM_TEST_FILES_BAG_KEY,
  type VmSession,
  type VmWorkerClient,
  writeGlobalState,
} from './shell/index.js'
export type {
  DrainRunOptions,
  DrainTestOutcome,
  DrainTestRef,
  HarnessModuleBuiltin,
  InterceptionRuntime,
  SnapshotClientLike,
  SnapshotEnvironmentLike,
  SnapshotEnvironmentOptions,
  SnapshotStackFrame,
  SnapshotStateOptionsLike,
  SnapshotSummaryLike,
  SnapshotSupport,
  VitestModuleNamespace,
  VmDiscoveredTestFiles,
  VmFileContext,
  VmGraphContext,
  VmPluginBag,
  VmPluginHost,
  VmRunContext,
  VmRunnerGlobalState,
  VmSessionPlugin,
  VmStageArgs,
  VmStageName,
  VmTestContext,
  VmTestOutcome,
} from './shell/index.js'
export { transformPlugin } from './shell/plugins/transform.js'
export { createVitestConfigPlugin, vitestConfigPlugin } from './shell/plugins/vitest-config.js'
export { createVmVitestRuntime, type VmVitestHostHandle } from './shell/vitest-host/bridge.js'
export {
  VM_VITEST_BAG_KEY,
  type VmProjectConfig,
  type VmTransformResult,
  type VmVitestConfig,
  type VmVitestRuntime,
} from './shell/vitest-host/runtime.js'
